#!/bin/bash
#
# Use Current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j n
#
# Run job through bash shell
#$ -S /bin/bash
#
# Your job name
#$ -N plots
#
# Send an email after the job has finished
#$ -m e
#$ -M fer_talavera@comunidad.unam.mx
#
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load samtools/1.9
#
# List of stats files to process
stats_files=(
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6752b.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6752c.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6753a.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6753b.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6753c.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6754a.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6754b.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6754c.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6755a.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6755b.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6755c.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6756a.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6756b.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6756c.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6757b.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6758a.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6758b.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6758c.dupmarked.stats
    /mnt/Adenina/drobles/ftalavera/vape_lung_cancer/1_quality_control/2_samtools_stats/MOUSE_GRCm38_pulldown_MD6760c.dupmarked.stats
)

# Process each stats file
for stats_file in "${stats_files[@]}"; do
    # Extract the base name of the file for output naming
    base_name=$(basename "$stats_file" .stats)
    # Create a directory for each plot output
    output_dir="${base_name}.graphs"
    mkdir -p "$output_dir"
    # Run plot-bamstats and save the output in the directory
    plot-bamstats -p "$output_dir/" "$stats_file"
done
