library("CopywriteR")

bp.param <- SnowParam(workers = 1, type = "SOCK")

name = "MD6753"

tumor_bam = paste("/mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_",name,"a/mapped_sample/MOUSE_GRCm38_pulldown_",name,"a.dupmarked.bam", sep="") 
normal_bam = paste("/mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_",name,"c/mapped_sample/MOUSE_GRCm38_pulldown_",name,"c.dupmarked.bam", sep="") 

sample.control = data.frame(samples=c(normal_bam,tumor_bam),controls=c(normal_bam,normal_bam))

CopywriteR(sample.control = sample.control,
             destination.folder = file.path(paste("/mnt/atgc-d1/drobles/ftalavera/copywriter/results/",name, sep="")),
             reference.folder = file.path("/mnt/atgc-d1/drobles/ftalavera/copywriter/precopywriter", "mm10_20kb"),
             capture.regions.file = file.path("/mnt/Adenina/drobles/mtalavera/mutect2/Allexon_v2_Covered_corrected.bed"), bp.param = bp.param)

plotCNA(destination.folder = file.path(paste("/mnt/atgc-d1/drobles/ftalavera/copywriter/results/",name, sep="")))
