#!/bin/bash
#
# Use Current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j n
#
# Run job through bash shell
#$ -S /bin/bash
#
# Your job name
#$ -N conpair_pileup
#
# Send an email after the job has finished
#$ -m e
#$ -M fer_talavera@comunidad.unam.mx
#$ -l vf=20G
#
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load gcc/5.1.0
module load conpair/0.2
module load gatk/3.3.0
#
# Define the reference and markers
reference=/mnt/atgc-d1/drobles/ftalavera/vaping_lung_cancer/somatic_profile/reference/Mus_musculus.GRCm38.68.dna.toplevel.fa
markers=/cm/shared/apps/conpair/0.2/data/markers/SureSelect_Mouse_All_Exon_V1_GRCm38_markers_MAF_0.4_LD_0.8.bed

# List of BAM files to process
bam_files=(
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6752b_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6753a_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6753b_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6754a_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6754b_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6755a_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6755b_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6756a_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6756b_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6758a_clip.bam
    /mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/data/MD6758b_clip.bam
)

# Output directory
output_dir=/mnt/atgc-d1/drobles/ftalavera/vape_lung_cancer/1_quality_control/4_conpair/1_pileup

# Process each BAM file
for bam_file in "${bam_files[@]}"; do
    # Extract the base name of the file for output naming
    base_name=$(basename "$bam_file" .dupmarked.bam)
    # Run the pileup command and save the output
    run_gatk_pileup_for_sample.py --reference "$reference" --markers "$markers" -B "$bam_file" -O "$output_dir/${base_name}_pileup.txt"
done
