#!/bin/bash
#
# Use Current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j n
#
# Run job through bash shell
#$ -S /bin/bash
#
# Your job name
#$ -N samtools_stats
#
# Send an email after the job has finished
#$ -m e
#$ -M fer_talavera@comunidad.unam.mx
#
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load samtools/1.9
#
# List of BAM files to process
bam_files=(
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6752b/mapped_sample/MOUSE_GRCm38_pulldown_MD6752b.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6752c/mapped_sample/MOUSE_GRCm38_pulldown_MD6752c.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6753a/mapped_sample/MOUSE_GRCm38_pulldown_MD6753a.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6753b/mapped_sample/MOUSE_GRCm38_pulldown_MD6753b.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6753c/mapped_sample/MOUSE_GRCm38_pulldown_MD6753c.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6754a/mapped_sample/MOUSE_GRCm38_pulldown_MD6754a.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6754b/mapped_sample/MOUSE_GRCm38_pulldown_MD6754b.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6754c/mapped_sample/MOUSE_GRCm38_pulldown_MD6754c.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6755a/mapped_sample/MOUSE_GRCm38_pulldown_MD6755a.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6755b/mapped_sample/MOUSE_GRCm38_pulldown_MD6755b.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6755c/mapped_sample/MOUSE_GRCm38_pulldown_MD6755c.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6756a/mapped_sample/MOUSE_GRCm38_pulldown_MD6756a.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6756b/mapped_sample/MOUSE_GRCm38_pulldown_MD6756b.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6756c/mapped_sample/MOUSE_GRCm38_pulldown_MD6756c.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6757b/mapped_sample/MOUSE_GRCm38_pulldown_MD6757b.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6758a/mapped_sample/MOUSE_GRCm38_pulldown_MD6758a.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6758b/mapped_sample/MOUSE_GRCm38_pulldown_MD6758b.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6758c/mapped_sample/MOUSE_GRCm38_pulldown_MD6758c.dupmarked.bam
    /mnt/Adenina/drobles/data/smoking_mice/PDexport/2499_MD6760c/mapped_sample/MOUSE_GRCm38_pulldown_MD6760c.dupmarked.bam

)

# Process each BAM file
for bam_file in "${bam_files[@]}"; do
    # Extract the base name of the file for output naming
    base_name=$(basename "$bam_file" .bam)
    # Run samtools stats and save the output
    samtools stats "$bam_file" > "${base_name}.stats"
done
